#!/bin/bash

set -e

echo "postBuild starting =================================================="
echo "==== env ========= =================================================="
env
echo "==== set ========= =================================================="
set
echo "==== end ========= =================================================="

# path_info branch
pip install -U git+https://github.com/ryanlovett/jupyter-server-proxy@da16a55

# path_info branch
pip install -U git+https://github.com/ryanlovett/jupyter-rsession-proxy@bfd51e5

# set rserver's --www-root-path
echo "export RSESSION_PROXY_RSTUDIO_1_4=1" >> /home/${NB_USER}/.bash_profile
